// flow-typed signature: 90f9439993d2fb97ef53e4306788a7b9
// flow-typed version: <<STUB>>/firebase-old_vhttps://github.com/traxicorp/firebase-old/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'firebase-old'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'firebase-old' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'firebase-old/app-node' {
  declare module.exports: any;
}

declare module 'firebase-old/app' {
  declare module.exports: any;
}

declare module 'firebase-old/auth-node' {
  declare module.exports: any;
}

declare module 'firebase-old/auth' {
  declare module.exports: any;
}

declare module 'firebase-old/database-node' {
  declare module.exports: any;
}

declare module 'firebase-old/database' {
  declare module.exports: any;
}

declare module 'firebase-old/externs/firebase-app-externs' {
  declare module.exports: any;
}

declare module 'firebase-old/externs/firebase-auth-externs' {
  declare module.exports: any;
}

declare module 'firebase-old/externs/firebase-client-auth-externs' {
  declare module.exports: any;
}

declare module 'firebase-old/externs/firebase-database-externs' {
  declare module.exports: any;
}

declare module 'firebase-old/externs/firebase-error-externs' {
  declare module.exports: any;
}

declare module 'firebase-old/externs/firebase-messaging-externs' {
  declare module.exports: any;
}

declare module 'firebase-old/externs/firebase-server-auth-externs' {
  declare module.exports: any;
}

declare module 'firebase-old/externs/firebase-storage-externs' {
  declare module.exports: any;
}

declare module 'firebase-old/firebase-app' {
  declare module.exports: any;
}

declare module 'firebase-old/firebase-auth' {
  declare module.exports: any;
}

declare module 'firebase-old/firebase-browser' {
  declare module.exports: any;
}

declare module 'firebase-old/firebase-database' {
  declare module.exports: any;
}

declare module 'firebase-old/firebase-messaging' {
  declare module.exports: any;
}

declare module 'firebase-old/firebase-node' {
  declare module.exports: any;
}

declare module 'firebase-old/firebase-react-native' {
  declare module.exports: any;
}

declare module 'firebase-old/firebase-storage' {
  declare module.exports: any;
}

declare module 'firebase-old/firebase' {
  declare module.exports: any;
}

declare module 'firebase-old/messaging' {
  declare module.exports: any;
}

declare module 'firebase-old/server-auth-node/auth' {
  declare module.exports: any;
}

declare module 'firebase-old/server-auth-node/credential' {
  declare module.exports: any;
}

declare module 'firebase-old/server-auth-node/index' {
  declare module.exports: any;
}

declare module 'firebase-old/server-auth-node/token-generator' {
  declare module.exports: any;
}

declare module 'firebase-old/storage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'firebase-old/app-node.js' {
  declare module.exports: $Exports<'firebase-old/app-node'>;
}
declare module 'firebase-old/app.js' {
  declare module.exports: $Exports<'firebase-old/app'>;
}
declare module 'firebase-old/auth-node.js' {
  declare module.exports: $Exports<'firebase-old/auth-node'>;
}
declare module 'firebase-old/auth.js' {
  declare module.exports: $Exports<'firebase-old/auth'>;
}
declare module 'firebase-old/database-node.js' {
  declare module.exports: $Exports<'firebase-old/database-node'>;
}
declare module 'firebase-old/database.js' {
  declare module.exports: $Exports<'firebase-old/database'>;
}
declare module 'firebase-old/externs/firebase-app-externs.js' {
  declare module.exports: $Exports<'firebase-old/externs/firebase-app-externs'>;
}
declare module 'firebase-old/externs/firebase-auth-externs.js' {
  declare module.exports: $Exports<'firebase-old/externs/firebase-auth-externs'>;
}
declare module 'firebase-old/externs/firebase-client-auth-externs.js' {
  declare module.exports: $Exports<'firebase-old/externs/firebase-client-auth-externs'>;
}
declare module 'firebase-old/externs/firebase-database-externs.js' {
  declare module.exports: $Exports<'firebase-old/externs/firebase-database-externs'>;
}
declare module 'firebase-old/externs/firebase-error-externs.js' {
  declare module.exports: $Exports<'firebase-old/externs/firebase-error-externs'>;
}
declare module 'firebase-old/externs/firebase-messaging-externs.js' {
  declare module.exports: $Exports<'firebase-old/externs/firebase-messaging-externs'>;
}
declare module 'firebase-old/externs/firebase-server-auth-externs.js' {
  declare module.exports: $Exports<'firebase-old/externs/firebase-server-auth-externs'>;
}
declare module 'firebase-old/externs/firebase-storage-externs.js' {
  declare module.exports: $Exports<'firebase-old/externs/firebase-storage-externs'>;
}
declare module 'firebase-old/firebase-app.js' {
  declare module.exports: $Exports<'firebase-old/firebase-app'>;
}
declare module 'firebase-old/firebase-auth.js' {
  declare module.exports: $Exports<'firebase-old/firebase-auth'>;
}
declare module 'firebase-old/firebase-browser.js' {
  declare module.exports: $Exports<'firebase-old/firebase-browser'>;
}
declare module 'firebase-old/firebase-database.js' {
  declare module.exports: $Exports<'firebase-old/firebase-database'>;
}
declare module 'firebase-old/firebase-messaging.js' {
  declare module.exports: $Exports<'firebase-old/firebase-messaging'>;
}
declare module 'firebase-old/firebase-node.js' {
  declare module.exports: $Exports<'firebase-old/firebase-node'>;
}
declare module 'firebase-old/firebase-react-native.js' {
  declare module.exports: $Exports<'firebase-old/firebase-react-native'>;
}
declare module 'firebase-old/firebase-storage.js' {
  declare module.exports: $Exports<'firebase-old/firebase-storage'>;
}
declare module 'firebase-old/firebase.js' {
  declare module.exports: $Exports<'firebase-old/firebase'>;
}
declare module 'firebase-old/messaging.js' {
  declare module.exports: $Exports<'firebase-old/messaging'>;
}
declare module 'firebase-old/server-auth-node/auth.js' {
  declare module.exports: $Exports<'firebase-old/server-auth-node/auth'>;
}
declare module 'firebase-old/server-auth-node/credential.js' {
  declare module.exports: $Exports<'firebase-old/server-auth-node/credential'>;
}
declare module 'firebase-old/server-auth-node/index.js' {
  declare module.exports: $Exports<'firebase-old/server-auth-node/index'>;
}
declare module 'firebase-old/server-auth-node/token-generator.js' {
  declare module.exports: $Exports<'firebase-old/server-auth-node/token-generator'>;
}
declare module 'firebase-old/storage.js' {
  declare module.exports: $Exports<'firebase-old/storage'>;
}
