// flow-typed signature: 078d1a8792cf71c3f1c13c4aa0579514
// flow-typed version: <<STUB>>/react-native-swiper_vhttps://github.com/brendan-rius/react-native-swiper/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-swiper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-swiper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-swiper/examples/App' {
  declare module.exports: any;
}

declare module 'react-native-swiper/examples/components/Basic/index' {
  declare module.exports: any;
}

declare module 'react-native-swiper/examples/components/Dynamic/index' {
  declare module.exports: any;
}

declare module 'react-native-swiper/examples/components/LoadMinimal/index' {
  declare module.exports: any;
}

declare module 'react-native-swiper/examples/components/Phone/index' {
  declare module.exports: any;
}

declare module 'react-native-swiper/examples/components/PhotoView/index' {
  declare module.exports: any;
}

declare module 'react-native-swiper/examples/components/Swiper/index' {
  declare module.exports: any;
}

declare module 'react-native-swiper/examples/components/SwiperNumber/index' {
  declare module.exports: any;
}

declare module 'react-native-swiper/examples/index.android' {
  declare module.exports: any;
}

declare module 'react-native-swiper/examples/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-swiper/examples/scripts/watch-and-copy-src' {
  declare module.exports: any;
}

declare module 'react-native-swiper/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-swiper/examples/App.js' {
  declare module.exports: $Exports<'react-native-swiper/examples/App'>;
}
declare module 'react-native-swiper/examples/components/Basic/index.js' {
  declare module.exports: $Exports<'react-native-swiper/examples/components/Basic/index'>;
}
declare module 'react-native-swiper/examples/components/Dynamic/index.js' {
  declare module.exports: $Exports<'react-native-swiper/examples/components/Dynamic/index'>;
}
declare module 'react-native-swiper/examples/components/LoadMinimal/index.js' {
  declare module.exports: $Exports<'react-native-swiper/examples/components/LoadMinimal/index'>;
}
declare module 'react-native-swiper/examples/components/Phone/index.js' {
  declare module.exports: $Exports<'react-native-swiper/examples/components/Phone/index'>;
}
declare module 'react-native-swiper/examples/components/PhotoView/index.js' {
  declare module.exports: $Exports<'react-native-swiper/examples/components/PhotoView/index'>;
}
declare module 'react-native-swiper/examples/components/Swiper/index.js' {
  declare module.exports: $Exports<'react-native-swiper/examples/components/Swiper/index'>;
}
declare module 'react-native-swiper/examples/components/SwiperNumber/index.js' {
  declare module.exports: $Exports<'react-native-swiper/examples/components/SwiperNumber/index'>;
}
declare module 'react-native-swiper/examples/index.android.js' {
  declare module.exports: $Exports<'react-native-swiper/examples/index.android'>;
}
declare module 'react-native-swiper/examples/index.ios.js' {
  declare module.exports: $Exports<'react-native-swiper/examples/index.ios'>;
}
declare module 'react-native-swiper/examples/scripts/watch-and-copy-src.js' {
  declare module.exports: $Exports<'react-native-swiper/examples/scripts/watch-and-copy-src'>;
}
declare module 'react-native-swiper/index' {
  declare module.exports: $Exports<'react-native-swiper'>;
}
declare module 'react-native-swiper/index.js' {
  declare module.exports: $Exports<'react-native-swiper'>;
}
declare module 'react-native-swiper/src/index.js' {
  declare module.exports: $Exports<'react-native-swiper/src/index'>;
}
