// flow-typed signature: f91d1c50689c6fe3f1732b186b4bb769
// flow-typed version: <<STUB>>/react-native-analytics_vhttps://github.com/traxicorp/react-native-analytics/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-analytics'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-analytics' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-analytics/index' {
  declare module.exports: $Exports<'react-native-analytics'>;
}
declare module 'react-native-analytics/index.js' {
  declare module.exports: $Exports<'react-native-analytics'>;
}
