// flow-typed signature: 2548852b31adb0fd19854482cb574f48
// flow-typed version: <<STUB>>/react-native-ab_vhttps://github.com/traxicorp/react-native-ab/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-ab'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-ab' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-ab/Experiment' {
  declare module.exports: any;
}

declare module 'react-native-ab/Variant' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-ab/Experiment.js' {
  declare module.exports: $Exports<'react-native-ab/Experiment'>;
}
declare module 'react-native-ab/index' {
  declare module.exports: $Exports<'react-native-ab'>;
}
declare module 'react-native-ab/index.js' {
  declare module.exports: $Exports<'react-native-ab'>;
}
declare module 'react-native-ab/Variant.js' {
  declare module.exports: $Exports<'react-native-ab/Variant'>;
}
