// flow-typed signature: cc7bd413c78160844848849e5251b3ce
// flow-typed version: <<STUB>>/react-static-container_v^1.0.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-static-container'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-static-container' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-static-container/lib/StaticContainer.react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-static-container/index' {
  declare module.exports: $Exports<'react-static-container'>;
}
declare module 'react-static-container/index.js' {
  declare module.exports: $Exports<'react-static-container'>;
}
declare module 'react-static-container/lib/StaticContainer.react.js' {
  declare module.exports: $Exports<'react-static-container/lib/StaticContainer.react'>;
}
