// flow-typed signature: 8a3ba95e09e17a4bf3c3765f51b72bf3
// flow-typed version: <<STUB>>/react-native-contacts_vlatest/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-contacts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-contacts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-contacts/index' {
  declare module.exports: $Exports<'react-native-contacts'>;
}
declare module 'react-native-contacts/index.js' {
  declare module.exports: $Exports<'react-native-contacts'>;
}
