// flow-typed signature: 830dcea4e7e7f4c8da51fcbe18a31b39
// flow-typed version: <<STUB>>/react-native-billing_vhttps://github.com/traxicorp/react-native-billing/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-billing'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-billing' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-billing/example/index.android' {
  declare module.exports: any;
}

declare module 'react-native-billing/example/index.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-billing/example/index.android.js' {
  declare module.exports: $Exports<'react-native-billing/example/index.android'>;
}
declare module 'react-native-billing/example/index.ios.js' {
  declare module.exports: $Exports<'react-native-billing/example/index.ios'>;
}
declare module 'react-native-billing/index' {
  declare module.exports: $Exports<'react-native-billing'>;
}
declare module 'react-native-billing/index.js' {
  declare module.exports: $Exports<'react-native-billing'>;
}
