// flow-typed signature: 0ac3c7ce171e84c4e36c25ca76c74e2d
// flow-typed version: <<STUB>>/react-native-sms-android_v^0.4.1/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-sms-android'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-sms-android' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-sms-android/index' {
  declare module.exports: $Exports<'react-native-sms-android'>;
}
declare module 'react-native-sms-android/index.js' {
  declare module.exports: $Exports<'react-native-sms-android'>;
}
