// flow-typed signature: 4c8cc6745fec1716168c9748a8a8462f
// flow-typed version: <<STUB>>/react-native-router-redux_v^0.2.2/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-router-redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-router-redux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-router-redux/src/actions' {
  declare module.exports: any;
}

declare module 'react-native-router-redux/src/Animations' {
  declare module.exports: any;
}

declare module 'react-native-router-redux/src/NavBar' {
  declare module.exports: any;
}

declare module 'react-native-router-redux/src/reducer' {
  declare module.exports: any;
}

declare module 'react-native-router-redux/src/TabBar' {
  declare module.exports: any;
}

declare module 'react-native-router-redux/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-router-redux/index' {
  declare module.exports: $Exports<'react-native-router-redux'>;
}
declare module 'react-native-router-redux/index.js' {
  declare module.exports: $Exports<'react-native-router-redux'>;
}
declare module 'react-native-router-redux/src/actions.js' {
  declare module.exports: $Exports<'react-native-router-redux/src/actions'>;
}
declare module 'react-native-router-redux/src/Animations.js' {
  declare module.exports: $Exports<'react-native-router-redux/src/Animations'>;
}
declare module 'react-native-router-redux/src/NavBar.js' {
  declare module.exports: $Exports<'react-native-router-redux/src/NavBar'>;
}
declare module 'react-native-router-redux/src/reducer.js' {
  declare module.exports: $Exports<'react-native-router-redux/src/reducer'>;
}
declare module 'react-native-router-redux/src/TabBar.js' {
  declare module.exports: $Exports<'react-native-router-redux/src/TabBar'>;
}
declare module 'react-native-router-redux/src/utils.js' {
  declare module.exports: $Exports<'react-native-router-redux/src/utils'>;
}
