// flow-typed signature: 09e41caee02fe357366bed73816a7f93
// flow-typed version: <<STUB>>/react-native-intercom_v5.8.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-intercom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-intercom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-intercom/lib/IntercomClient' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-intercom/lib/IntercomClient.js' {
  declare module.exports: $Exports<'react-native-intercom/lib/IntercomClient'>;
}
