// flow-typed signature: 3ee2b7fa701980a2f1dead70bc183872
// flow-typed version: <<STUB>>/react-native-image-picker_v^0.26.2/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-image-picker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-image-picker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-image-picker/index' {
  declare module.exports: $Exports<'react-native-image-picker'>;
}
declare module 'react-native-image-picker/index.js' {
  declare module.exports: $Exports<'react-native-image-picker'>;
}
