# vim: set syntax=ruby:
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'traxi' do
  # Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  # Fabric
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Analytics'
  pod 'Segment-Mixpanel'
  pod 'Segment-GoogleAnalytics'

  # Intercom
  pod 'Intercom'
end
